### ISSUE TITLE
o2ac-ur pull access denied

### ISSUE THREAD

**Issue by iamrajee** [o2ac/o2ac-ur#4]
Dear @felixvd and team, first of all, thank you for the wonderful work!

I'm getting ```o2ac-ur  pull access denied``` error as below. I'm new to dockers, not sure how can I resolve it. I would really appreciate it if you can look into this. Thank you.

```
rajendra@u18:~/o2ac-ur$ ./BUILD-DOCKER-IMAGE.sh
./BUILD-DOCKER-IMAGE.sh: DOCKER_PROJECT=rajendra
./BUILD-DOCKER-IMAGE.sh: DOCKER_CONTAINER=rajendra_o2ac-ur_1
fatal: ambiguous argument 'docker/Dockerfile': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Login to registry.gitlab.com... Enter your username and password:
Username: iamrajee
Password: 
WARNING! Your password will be stored unencrypted in /home/rajendra/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Pulling o2ac-ur ... error

ERROR: for o2ac-ur  pull access denied for registry.gitlab.com/o2ac/o2ac-ur/o2ac-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for registry.gitlab.com/o2ac/o2ac-ur/o2ac-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Building o2ac-ur
Step 1/68 : FROM nvidia/cudagl:10.1-devel-ubuntu18.04
10.1-devel-ubuntu18.04: Pulling from nvidia/cudagl ...
```

**Comment by felixvd** [comment]
Hey @iamrajee ,

Please excuse the confusion: the script shows an error, but this is not an obstacle. You should be able to proceed through the rest of the build instruction without doing anything about this. The error just means that you will build the image locally, which will take about 45 minutes or so, instead of downloading it. 

This happens because the registry still points to our old (private) repo location. I just don't have time to update it to use the Github registry instead.

Let me know if you get stuck on anything, so we can fix the instructions!

**Comment by iamrajee** [comment]
Thank you for your prompt response. While running other scripts I got a few errors, but I'm not sure if they are critical. So as you mentioned I'll proceed anyway. 
Below are the logs I get while running these:
[BUILD-DOCKER-IMAGE.sh](https://gist.github.com/iamrajee/f45abb11c5c8592a40dc37a04762b5eb)
[SETUP-DEVEL-MACHINE.sh(on running 3rd time))](https://gist.github.com/iamrajee/31b41e7bb360635ac6d91ce4435173d1)

I will continue for now, and update here if I face any roadblocks.

**Comment by felixvd** [comment]
`SETUP-DEVEL-MACHINE.sh` seems to have finished without problems. I assume you rebooted at least once.

The log from `BUILD-DOCKER-IMAGE.sh` has a lot of empty lines - was there an issue with your terminal while copying this?

**Comment by iamrajee** [comment]
No, It was also empty lines in the terminal as well. I have modified my terminal to record the last 20k lines, so I don't think it might be the terminal problem.

Sure, I'll look into `Dockerfile` configurations.

**Comment by iamrajee** [comment]
Also, I was curious if this can be done seamlessly without docker?
I tried to copy packages from overlay_ws into catkin_ws and tried `catkin_make_isolated` but I get the below error:
(I'd install all the dependencies using rosdep). Do I really need packages from overlay_ws, or can I ignore them?
<details close>
 <summary> Error log</summary>
```
==> Processing catkin package: 'aist_handeye_calibration'
==> cmake /home/rajendra/o2ac-ur/catkin_ws/src/aist_modules/aist_handeye_calibration -DCATKIN_DEVEL_PREFIX=/home/rajendra/o2ac-ur/catkin_ws/devel_isolated/aist_handeye_calibration -DCMAKE_INSTALL_PREFIX=/home/rajendra/o2ac-ur/catkin_ws/install_isolated -G Unix Makefiles in '/home/rajendra/o2ac-ur/catkin_ws/build_isolated/aist_handeye_calibration'
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Using CATKIN_DEVEL_PREFIX: /home/rajendra/o2ac-ur/catkin_ws/devel_isolated/aist_handeye_calibration
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/rajendra/o2ac-ur/catkin_ws/build_isolated/aist_handeye_calibration/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
mktemp: failed to create file via template ‘/tmp/setup.sh.XXXXXXXXXX’: Read-only file system
Traceback (most recent call last):
  File "/home/rajendra/o2ac-ur/catkin_ws/build_isolated/aist_handeye_calibration/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/home/rajendra/o2ac-ur/catkin_ws/devel_isolated/aist_handeye_calibration/env.sh')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/environment_cache.py", line 63, in generate_environment_script
    env_after = ast.literal_eval(output.decode('utf8'))
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Could not create temporary file: 
                   ^
SyntaxError: invalid syntax
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python2
  "/home/rajendra/o2ac-ur/catkin_ws/build_isolated/aist_handeye_calibration/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/all.cmake:208 (safe_execute_process)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/rajendra/o2ac-ur/catkin_ws/build_isolated/aist_handeye_calibration/CMakeFiles/CMakeOutput.log".
See also "/home/rajendra/o2ac-ur/catkin_ws/build_isolated/aist_handeye_calibration/CMakeFiles/CMakeError.log".
<== Failed to process package 'aist_handeye_calibration': 
  Command '['cmake', '/home/rajendra/o2ac-ur/catkin_ws/src/aist_modules/aist_handeye_calibration', '-DCATKIN_DEVEL_PREFIX=/home/rajendra/o2ac-ur/catkin_ws/devel_isolated/aist_handeye_calibration', '-DCMAKE_INSTALL_PREFIX=/home/rajendra/o2ac-ur/catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/rajendra/o2ac-ur/catkin_ws/build_isolated/aist_handeye_calibration && cmake /home/rajendra/o2ac-ur/catkin_ws/src/aist_modules/aist_handeye_calibration -DCATKIN_DEVEL_PREFIX=/home/rajendra/o2ac-ur/catkin_ws/devel_isolated/aist_handeye_calibration -DCMAKE_INSTALL_PREFIX=/home/rajendra/o2ac-ur/catkin_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.
```
</details>

**Comment by iamrajee** [comment]
Maybe un-related but while opening the new terminal after all this, I'm getting
```
mktemp: failed to create file via template ‘/tmp/setup.sh.XXXXXXXXXX’: Read-only file system
Could not create temporary file:
```
Also, apparently, catkin_make is not found as
```
rajendra@u18:~/drone_ws$ catkin_make
Command 'catkin_make' not found, but can be installed with:
sudo apt install catkin
```
Could it be because of docker, do I need to stop docker before working normally?
I tried `sudo mount -a` but didn't help. Is it related to [this](https://unix.stackexchange.com/questions/409954/mktemp-failed-to-create-directory-via-template-permission-denied). Thank you for your time and apologies for asking the simple queries, I'm a novice with docker.

**Comment by felixvd** [comment]
You can run `BUILD-DOCKER-IMAGE.sh` as many times as you want. It will just build the image that the container will be based on.

The instructions assume that you will `catkin build` the workspace from inside the docker container, not in your host OS. Until you built the docker image and can run `RUN-DOCKER-CONTAINER.sh` it's not surprising that building the workspace fails. And yes, you need the `underlay_ws` to be configured correctly. Inside the container you can simply run `o2ac-reset-catkin-workspace` or `o2ac-build-catkin-workspace` which sets it up automatically.

Also yes, there's something up with the `read-only file system`. I've never seen that before. Is there an issue with your user not being in the `docker` group maybe?
